service: default

runtime: python27
api_version: 1
threadsafe: true

handlers:
  - url: /
    static_files: public/index.html
    upload: public/index\.html

  - url: /datastore/.*
    script: application.Bootstrap.application

  - url: /(.*)
    static_files: public/\1
    upload: public/(.*)

libraries:
  - name: webapp2
    version: latest
